---
title: "R Notebook"
output: html_notebook
---

```{r}

# alog_input = "C:/W_shortcut/coffeeroastingprofiles/data-raw/21-02-17_1840_ZambiaKasama_1stcrack.alog"
# alog_input = "C:/Users/jacci/Documents/DS 710/coffee_roasting_profiles/data-raw/21-02-17_1840_ZambiaKasama_1stcrack.alog"
alog_input = "C:/Users/jacci/Documents/DS 710/coffee_roasting_profiles/data-raw/21-02-09_2015_Haiti_Baptiste.alog"
```

```{r open alog}
   sub <- readLines(alog_input) # open_profile_as_json function
    # incomplete final line found on (c..) - could be bc you need to add line at
    # end of json Must replace ' and change True/False so it has quotes in order
    # to read as a JSON
    sub <- gsub("\\'", '"', sub)
    sub <- gsub("True", '\"True\"', sub)
    sub <- gsub("False", '\"False\"', sub)
    
    profile_as_json <- jsonlite::fromJSON(sub)
    # y <- jsonlite::fromJSON(sub, flatten =TRUE, simplifyDataFrame = TRUE)
    # wont save as JSON??
# jsonlite::toJSON(sub)
    # profile_as_json[["timex %>% as.data.frame()
    x <- jsonlite::toJSON(profile_as_json) # works! but more branches
    write(x, paste0("C:/Users/jacci/Documents/DS 710/coffee_roasting_profiles/data-raw/saved/","test_haiti.json"))
    jsonlite::toJSON(sub) # doesnt work
```
```{r}
# these were copied into fct_upload_json_data
# TO make profile chart
get_special_event_times <- function(json_file) {
    tibble(time_of_event = json_file[["specialevents"]],
           type_of_event = json_file[["specialeventsStrings"]])
}

get_data_of_times_temps <- function(json_file) {
    tibble(time = json_file[["timex"]],
           BT = json_file[["temp1"]],
           ET = json_file[["temp2"]])
}

get_event_times <- function(json_file) {
    tibble(
        tp_time = json_file[["computed"]][["TP_time"]],
        dry_time = json_file[["computed"]][["DRY_time"]],
        fc_time_start = ifelse(is.null(json_file[["computed"]][["FCs_time"]]), 0, json_file[["computed"]][["FCs_time"]]),
        fc_time_end = ifelse(is.null(json_file[["computed"]][["FCe_time"]]), 0, json_file[["computed"]][["FCe_time"]]),
        sc_time_start = ifelse(is.null(json_file[["computed"]][["SCs_time"]]), 0, json_file[["computed"]][["SCs_time"]]),
        sc_time_end = ifelse(is.null(json_file[["computed"]][["SCe_time"]]), 0, json_file[["computed"]][["SCe_time"]]),
        drop_time = json_file[["computed"]][["DROP_time"]]
    )
}

# Make chart of %
get_data_of_phase_times <- function(json_file) {
    tibble(
        dryphase = json_file[["computed"]][["dryphasetime"]],
        midphase = json_file[["computed"]][["midphasetime"]],
        developphase = json_file[["computed"]][["finishphasetime"]]
    )
}

# display this at upload # CHECK IF NO DROP TIME check
get_data_to_display_at_upload <- function(json_file) {
    weight_loss_var = ifelse(is.null(json_file[["computed"]][["weight_loss"]]), 0, json_file[["computed"]][["weight_loss"]])
    tibble(
        "Roast date" = json_file[["roastisodate"]],
        "Roast time" = json_file[["roasttime"]],
        "Weight before" = as.character(json_file[["computed"]][["weightin"]]),
        "Weight after" = as.character(json_file[["computed"]][["weightout"]]),
        "Weight loss" = paste0(weight_loss_var, "%"),
        "Weight units" = json_file[["weight"]][3],
        "Bean notes" = json_file[["beans"]] # notes
    )
}
get_special_event_times(profile_as_json)
x <- get_data_of_times_temps(profile_as_json)
get_event_times(profile_as_json)
get_data_of_phase_times(profile_as_json)
get_data_to_display_at_upload(profile_as_json)    
    # %>% pivot_longer(cols = 1:7, values_to = "data")
# profile_as_json[["roastertype"]]
# profile_as_json[["heavyFC"]] # ??
# profile_as_json[["computed"]][["finish_phase_AUC"]]
# device = profile_as_json[["devices"]]
```
```{r}
get_data_to_display_at_upload(profile_as_json) %>% pivot_longer(cols = 1:7, values_to = "data")  %>% kableExtra::kbl(
        col.names = c("", ""), align = "l", centering = FALSE
    ) %>%  kableExtra::kable_minimal()
    ```
```{r}
2:30 219.5 deg line 14210
90 sec
Delta T = (changeTemp/ChangeTime)*60. =  degress per minute 
```
