---
title: "R Notebook"
output: html_notebook
---
```{r}
library(magrittr)
profile <- clean_raw_alog(alog)
# filename2 <-
# jsonlite::toJSON("C:/Users/jacci/Documents/DS 710/coffee_roasting_profiles/data-raw/saved/Angola--2021-02-26-16-16-22.json")
```
```{r}
phase_times = get_data_of_phase_times(profile) %>%
  tidyr::pivot_longer(everything(), values_to = "phase_time") %>%
  dplyr::mutate(name = factor(.data$name, levels = c("Dry", "Mid", "Dev"))) %>% # add levels
  dplyr::mutate(
    percent = as.character(round(
      .data$phase_time * 100 / sum(.data$phase_time), 1
    )),
    # Get phase percent
    phase_time_mid = format(lubridate::as_datetime(cumsum(.data$phase_time)), "%M:%S"),
    phase_time = format(lubridate::as_datetime(.data$phase_time), "%M:%S")
  )
# dplyr::mutate_if(is.integer, lubridate::as_datetime) %>%
# dplyr::mutate_if(is.numeric, lubridate::as_datetime)
# Get start times of each phase so that is where the label start. Add 1 to offset label.
phase_times[phase_times$name == "Dry", "label_point"] = "00:00"
phase_times[phase_times$name == "Mid", "label_point"] = phase_times[phase_times$name == "Dry", "phase_time_mid"]# + 1
phase_times[phase_times$name == "Dev", "label_point"] = phase_times[phase_times$name == "Mid", "phase_time_mid"] #+ 1
# colnames(profile)
    # colors for the 3 phase bars on top
      phase_colors <- c('#4DB848', '#FF9673', '#E1C8B4')

times_temps_deltas_as_df <- function(df = profile) {
  data.frame(
    "time" = unlist(df$time),
    "dtemp1" = unlist(df$dtemp1),
    "dtemp2" = unlist(df$dtemp2),
    "timex" = unlist(df$timex),
    "Time1" = unlist(df$Time1),
    "Time2" = unlist(df$Time2),
    "BT" = unlist(df$BT),
    "ET" = unlist(df$ET),
    "Event" = unlist(df$Event)
  ) # %>% dplyr::slice(-c(1:36))
}
```

```{r}
times_temps <- times_temps_deltas_as_df(profile) #%>% dplyr::mutate_if(is.character, as.integer)
# special_times <- get_special_event_times(json_file)
# 
#   # FC, phase times
#   event_times <-
#     get_event_times(json_file)

  plotly::plot_ly(
    data = times_temps,
    x = ~ Time2 # Time2 starts at charge time
  ) %>%
    plotly::add_lines(
      data = times_temps,  # ET Line
      type = 'scatter',
      mode = 'lines',
      line = list(color = "#4DB848"),
      y = ~ BT,
      # hovertemplate = paste('%{y: .1f}\u00b0F', '<br>%{x}<br>'),
      hovertemplate = '%{y: .1f}\u00b0F',
      showlegend = FALSE,
      name = "BT"
    ) %>%
    plotly::add_lines(
      data = times_temps,  # ET Line
      type = 'scatter',
      mode = 'lines',
      line = list(color = "#D50032"),
      y = ~ ET,
      # hovertemplate = paste('%{y: .1f}\u00b0F', '<br>%{x}<br>'),
      hovertemplate = '%{y: .1f}\u00b0F',
      showlegend = FALSE,
      name = "ET"
    ) %>%
    plotly::layout(hovermode = "x unified") %>%
    # plotly::add_annotations( # Special events
    #   data = special_times,
    #   x =  ~ lubridate::as_datetime(as.numeric(time_of_event)),
    #   # y = ~ jitter(400, 60),
    #   y = ~ 10,
    #   text = ~ type_of_event,
    #   # yaxis = "y2",
    #   textposition = "top center",
    #   showarrow = FALSE,
    #   # arrowhead = .5,
    #   # arrowwidth = 1,
    #   font = list(size = 12, color = "#ffffff"),
    #   bgcolor = ~ color
    # ) %>%                     # Add lines for phases
    plotly::add_lines(
      data = times_temps,        # Change BT Line
      mode = 'lines',
      x = ~ Time2,
      y = ~ dtemp1,
      line = list(color = "#428BCA"),
      name = "\u0394ET",
      hovertemplate = '%{y: .1f}\u00b0F',
      showlegend = FALSE,
      yaxis = "y2"
    ) %>%
    plotly::add_lines(
      data = times_temps,        # Change ET Line
      mode = 'lines',
      x = ~ Time2,
      y = ~ dtemp2,
      line = list(color = "#3f0585"),
      name = "\u0394BT",
      hovertemplate = '%{y: .1f}\u00b0F',
      showlegend = FALSE,
      yaxis = "y2"
    ) %>%
    plotly::layout(
       xaxis = list(# gridcolor = toRGB("gray85"),
          title = "",
          zeroline = F,
          showline = F,
          showgrid = F,
          # tick0 = "00:00",
          tick0 = 0,
          ticks = "inside",
          tickcolor = "rgb(245,245,245)",
          tickformat = "%M:%S",
          # tickmode = "linear",
          dtick = 30 # Tick every 30 seconds
     ),
      # The right side y-axis
      yaxis2 = list(
        zeroline = F,
        showline = F,
        showgrid = F,
        tickfont = list(color = "#428BCA"),
        ticksuffix = "\u00b0F",
        overlaying = "y",
        side = "right",
        title = ""
      ),
      yaxis = list(
        title = "",
        ticksuffix = "\u00b0F",
        zeroline = F,
        showline = F,
        showgrid = F
      ),
      margin = list(
        r = 30,
        l = 0,
        b = 0,
        t = 0
      ),
      plot_bgcolor = '#fff',
      # make white background
      paper_bgcolor = '#fff'
    ) %>% # Add 3 phases on top
    plotly::add_bars(
      data = phase_times,
      x =~ phase_time,
      y = ~ 500,
      name =  ~ name,
      width = 25,
      text =~ name, #?
      orientation = 'h',
      showlegend = FALSE,
      marker = list(color = phase_colors)
    ) %>%
    plotly::layout(barmode = 'stack') %>%
    plotly::add_text(data = phase_times, x =~ label_point, text =~ paste0(name,": ",percent,"%"),y = 500, textposition = "right", textfont = list(size = 12, color = "#ffffff"))
```
```{r}
# mess with format

x=lubridate::as_datetime(as.numeric(times$time))
lubridate::hms(x)
lubridate::minute(x)
lubridate::seconds(x)
lubridate::seconds_to_period(as.numeric(times$time)) %>% lubridate::ms() # THIS?
lubridate::fast_strptime(x, format = "%H%M")
(parse_date_time2(times$time))

sub(":\\d{2}", "", times((minutes%/%60 +  minutes%%60 /3600)/24))

as.numeric(times$time)%/%60  +  as.numeric(times$time)%%60 /3600
```
```{r test}
plotly::plot_ly(
  # BT Line
  times_temps,
  type = 'scatter',
  mode = 'lines',
  x = ~ Time2,
  line = list(color = "#4DB848"),
  # x = ~seq(ms("00:00"), ms("10:10")),
  # x = ~ lubridate::ms(Time2),
  # x = ~ lubridate::as_datetime(Time1),
  y = ~ BT,
  # hovertemplate = paste('%{y: .1f}\u00b0F', '<br>%{x}<br>'),
  hovertemplate = '%{y: .1f}\u00b0F',
  showlegend = FALSE,
  name = "BT"
) %>% plotly::layout(
        xaxis = list(# gridcolor = toRGB("gray85"),
          title = "",
          zeroline = F,
          showline = F,
          showgrid = F,
          # tick0 = "00:00",
          tick0 = 0,
          ticks = "inside",
          tickcolor = "rgb(245,245,245)",
          tickformat = "%M:%S",
          # tickmode = "linear",
          dtick = 30 # Tick every 30 seconds
     ))
```


